[in progress] Create 2 executable for bolt and add ros2 launch
open-dynamic-robot-initiative/bolt pull request #9
Opened 2021-10-19 07:33 UTC by Lhumd

[//]: # "Thanks for your contribution.  To make life of the reviewers easier,"
[//]: # "please give this pull request a meaningful title and provide the"
[//]: # "requested information below."

Add safe mode and make it able to run with single process.

## Description

[//]: # "Description of what you did.  If it is more complex, consider to add a"
[//]: # "'Summary' section."

Add safe mode, 
## How I Tested
By testing it on robot.

[//]: # "Explain how you tested your changes"

## Do not merge before

[//]: # "Link other open pull request here that need to be merged first."
[//]: # "Remove this section if it does not apply."

- [ ] link to dependent pull request

## I fulfilled the following requirements

[//]: # "Please make sure you followed these steps before requesting a review."
[//]: # "Check the boxes in the list below, when done."

- [ ] All new code is formatted according to our style guide (for C++ run clang-format, for Python, run flake8 and fix all warnings).
- [ ] All new functions/classes are documented and existing documentation is updated according to changes.
- [ ] No commented code from testing/debugging is kept (unless there is a good reason to keep it).

2021-10-29 07:32 UTC, MaximilienNaveau requested changes
First review done

2021-10-29 07:32 UTC, MaximilienNaveau commented on include/bolt/dgm_bolt.hpp
> +    /**
this is a copy of the documentation above, to be removed

2021-10-29 07:32 UTC, MaximilienNaveau commented on launch/bolt_bringup.launch.py
> +            Node(
nice

2021-10-29 07:32 UTC, MaximilienNaveau commented on launch/bolt_bringup.launch.py
> +                package="bolt",
won't work as you need sudo

2021-10-29 07:32 UTC, MaximilienNaveau commented on src/CMakeLists.txt
> +  add_executable(dg programs/dg.cpp)
target names needs more verbosity, at least the package name:
bolt_dg
bolt_hw

2021-10-29 07:32 UTC, MaximilienNaveau commented on src/CMakeLists.txt
> +  add_executable(hw programs/hw.cpp)
see previous comment

2021-10-29 07:32 UTC, MaximilienNaveau commented on src/programs/hw.cpp
> + * DynamicGraphManager for bolt main executbale.
typo

2021-11-19 15:10 UTC, MaximilienNaveau requested changes

2021-11-19 15:10 UTC, MaximilienNaveau commented on src/dgm_bolt.cpp
> +    return false;
... dangerous!!!!

2021-11-19 15:10 UTC, MaximilienNaveau commented on src/CMakeLists.txt
> +         "robot_properties_bolt/resources/odri_control_interface/"
Good point!

2021-11-25 17:08 UTC, Lhumd commented on launch/bolt_bringup.launch.py
> +                package="bolt",
Then I remove the bolt bringup.launch.py

2021-11-25 17:10 UTC, MaximilienNaveau commented on launch/bolt_bringup.launch.py
> +                package="bolt",
That's what I did, I run this node by hand and then use a ros2 launch for the rest of the application

2021-11-25 18:28 UTC, merged